### ISSUE TITLE
Individuals with different `mutation_type`s undergo different mutations

### ISSUE THREAD

**Issue by swom** [swom/ArchitectureEvolution#130]
Depends on:
- [x] #110 
- [x] #112

The following test should pass in individual.cpp 
```
```
*Note to self, this will be very similar to test for #112

**Comment by Clemcarle** [comment]
I think this is already tested in #112 . The test checks that the two networks have different weights and different activation levels at the end. So we know they undergo different mutations. Do we want a test to check they undergo exactly the type of mutation we meant them to have?
