### ISSUE TITLE
There should be an inpu to signal whihc environment function is being used to calculate the optima

### ISSUE THREAD

**Issue by swom** [swom/ArchitectureEvolution#138]

**Comment by Clemcarle** [comment]
What do you mean? Like an input node indicating which function is currently in use? 
I am not sure I will be using that, as I think I am mostly interested in adaptation speed upon change and I don't want there to be a possibility of networks finding a plastic response that can deal with both env functions. But if you think you'd like to use it we can implement it ; The main problem I see is that this input would not be very useful as a double (unless I'm not thinking about it in the right way, very possible), but to make it not-a-double we would need to completely change how nodes work.
