### ISSUE TITLE
Speed up test for #39

### ISSUE THREAD

**Issue by swom** [swom/ArchitectureEvolution#69]
Hey Clemio,
Let me know in the comment what you think. I would like to give this issue to you as a bit of a challenge to solve. I went and checked, and indeed there is a very clear reason why this test now runs forever. And this reason might cause us trouble in the future, as simulations might then also run for forever. I would like, as a first step, for you to try and identify where the problem might be, and let me knwo in the comments of this issue.
Let me know if you would like to try this way, or if you would orefer an explicit solution from me. 
If you would like to try, then good luck with your first optimization mistery case!

**Comment by swom** [comment]
You accept the case? 🔍

**Comment by Clemcarle** [comment]
It seems to be caused by the `are_same_env_function` function being slow and being called each time there is a change in environment.

**Comment by Clemcarle** [comment]
Accepted and solved(?)  !

**Comment by swom** [comment]
Ehe, yes indeed. then let's continue on #71

**Comment by swom** [comment]
case closed
