### ISSUE TITLE
Change the way we check one function is on and the other is not

### ISSUE THREAD

**Issue by swom** [swom/ArchitectureEvolution#71]
When switching optimum functions `are_the_same_function()` takes a very long time.
We need a faster way to fix this, write an issue and a test proposing a faster solution. You have many ways of doing this:
-1 making `are_the_same_function()` more efficient
-2 changing some parts of the design (look at the tresinformal game for inspiration maybe?)

**Comment by Clemcarle** [comment]
```c++
bool are_same_env_functions(const std::function<double(std::vector<double>)> &lhs,
                            const std::function<double(std::vector<double>)> &rhs)
{
    std::vector<double> weird_numbers{1234.5678, 98765.432, 7687687686};

  double lhs_optimal = lhs(weird_numbers);
  double rhs_optimal = rhs(weird_numbers);

  return lhs_optimal == rhs_optimal;

}
```

This is a more efficient solution, but I'm not sure if it is rigorous enough?

**Comment by swom** [comment]
Indeed it might not be the most rigorous, and we want to keep `are_the_same_function()` rigororous for tests. Can you think of other solutions?

**Comment by Clemcarle** [comment]
The second answer here 

https://stackoverflow.com/questions/20833453/comparing-stdfunctions-for-equality

seems to have a solution but it is not code I can understand.

**Comment by swom** [comment]
Ahaha I see you are going down the windy path of function comparison.
Have you had a look to the tresinformal game? Do you think the only way to speed this up is to find a faster way of comparing functions, or are there any work arounds?
